In [48]:
import numpy as np #業界簡稱np
import pandas as pd #業界簡稱pd

s1=pd.Series(np.arange(4.0,step=1.0),index=['a','b','c','d']) 
s1
#range不能有小數點 arange可以有小數點 
#每次遞增0.2 內建的range做不到 numpy的arange才作得到



a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [49]:
display(s1)
s1[0]

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

/tmp/ipykernel_26548/1551149800.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]


0.0

In [50]:
s1['a']

0.0

In [51]:
s1[['a','b','d']]  #[]subscrip就是用來抓東西=選取。若只要a.b.d。比numpy多了索引很像dictionary

a    0.0
b    1.0
d    3.0
dtype: float64

In [52]:
s1[-2:]*2    #只要最後三筆-2 #還可做陣列運算 #*=複合指定運算子

c    4.0
d    6.0
dtype: float64

In [53]:
s1           #*並沒有改變

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [54]:
s1[-2:]*=2   #*=複合指定運算子 #s1會改變

In [55]:
s1           #*=s1有改變 

a    0.0
b    1.0
c    4.0
d    6.0
dtype: float64

In [56]:
np.arange(16) #16個等於 0到15

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [57]:
np.reshape(np.arange(16),(4,4) )  #4*4=16


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [58]:
np.reshape(np.arange(16),(8,2) ) #8個列，2個欄

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [59]:
#一般不會放兩個fuction #實體有資料
data=np.arange(16).reshape((4,4)) #二維資料(有欄、有列)可以轉成dataframe表格
dataFrame=pd.DataFrame(data,
            index=['台北','台中','台南','高雄'],     　#列的名稱
            columns=['one','two','three','four'])  　#欄的名稱
dataFrame
            


SyntaxError: invalid non-printable character U+3000 (3128809985.py, line 4)

In [ ]:
#SUBSCRIP[]是選取"欄"
dataFrame['one']

台北     0
台中     4
台南     8
高雄    12
Name: one, dtype: int64

In [ ]:
dataFrame[['one','two']]

one  two
台北    0    1
台中    4    5
台南    8    9
高雄   12   13

In [ ]:
display(dataFrame)
dataFrame.loc['台北']  #loc已列為主

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7
台南    8    9     10    11
高雄   12   13     14    15

one      0
two      1
three    2
four     3
Name: 台北, dtype: int64

In [ ]:
dataFrame.loc[['台北','台中']]

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7

In [ ]:
#iloc，i就是用index，每欄每列都有預設但你看不到的0.1.2.3
dataFrame.iloc[[0,1]]

one  two  three  four
台北    0    1      2     3
台中    4    5      6     7

In [ ]:
#同時抓欄、列
dataFrame.loc[['台北','台中']][['one','two']] #list+subscript、list+subscript

one  two
台北    0    1
台中    4    5

In [61]:
dataFrame.iloc[[0,1],[0,1]]  #iloc只能用0.1.2.3

one  two
台北    0    1
台中    4    5